### ISSUE TITLE
mailman-request@ doesn't work because SYSTEM_ALIASES_PIPE_TRANSPORT is not set

### ISSUE THREAD

**Issue by shevek** [Angatar/mailman2#10]
None of the mailman aliases in /etc/aliases work. Exim issues `pipe_transport unset in system_aliases router`

The solution is something like:
```
.ifndef SYSTEM_ALIASES_PIPE_TRANSPORT
SYSTEM_ALIASES_PIPE_TRANSPORT = address_pipe
SYSTEM_ALIASES_USER = Debian-exim
SYSTEM_ALIASES_GROUP = daemon
.endif
```
somewhere in the main section of the split config.

**Comment by Angatar** [comment]
Hi Shevek,

The "yourlist"-request@ commands are well working out of the container.
 The initial mailman aliases in /etc/aliases are just set by default with the creation of the "dumb" mailman initial mailing list but are not in use with the container.

Actually the real mailman mailing lists commands aliases are defined within the "[40_mailman_pipe](https://github.com/Angatar/mailman2/blob/master/conf/40_mailman_pipe)" config file

BTW, it seems it is not considered anymore as a good practice to enable exim pipe_transport for Debian-exim since it might grant privileges to non-trusted processes ;)
