### ISSUE TITLE
Stops sending emails after rebooting the docker host

### ISSUE THREAD

**Issue by optiprime** [Angatar/mailman2#11]
I am using the docker-compose variant which works fine until I reboot my docker host. After that emails to maillists are accepted but not conveyed any longer.

I investigated this issue futher and found out that mailan's qrunner lock files are not deleted when stopping the container. Manually deleting the files solved the problem temporarily: `docker-compose exec mailman bash -c "rm -f /var/run/lock/mailman/*"; docker-compose restart`

I also observed that `docker-compose stop`  takes 10 seconds - thats the default timeout after which the processes are forcibly terminated. Increasing the timeout (compose option `stop_grace_period: 3m` ) leads to same result.

I shortly inspected /run.sh. Here the mailman process is started by `/etc/init.d/mailman start`  but never stopped when catching a SIGTERM signal. Consequently a container restart does not cleanup the locks which inhibits queue processing.

**Comment by Angatar** [comment]
Hi, Thx for reporting this... usually prod servers are quite stable and as we schedule to destroy containers on a regular basis to replace them with new ones so that we are close to immutability, we never encountered this issue before.
BTW, this container declares volumes for important data (lists, archives, tls cert...) so they won't disappear after container replacement.
But you are right, a graceful stop of the processes in this container while a "docker stop" is asked is consistent (containers are too often maltreated as they are replaceable) and it would fix immediately this stop/start issue in case of a server reboot so that it won't have to wait a container replacement to be fixed.
The "docker stop"  command sends an initial SIGTERM signal to PID1 and if no termination happens during the defined grace period it kills them with a SIGKILL. As this container was conceived rather like a convenient mailing list tools deployment than a standard functional container the PID1 is given to the run.sh start script that runs several services and indeed doesn't transmit, for now, the termination signal to the services started. 

So I'm gonna add a few lines ASAP to the run.sh script to stop the services properly when a SIGTERM is received.
I'll tell you when the updated script is pushed so that you can pull the new d3fk/mailman2:latest container version.

**Comment by Angatar** [comment]
The new version of the run.sh script has now been pushed and the container automatically built by Docker Hub ... a simple `docker pull d3fk/mailman2` before deploying a new mailman container should fix this issue on your next server reboot or container stop/start cycle.

**Comment by optiprime** [comment]
Your fix has worked excellently. Thank you very much! :-)
