### ISSUE TITLE
Apache SSL certificate are not exposed as a docker volume

### ISSUE THREAD

**Issue by rapmankin** [Angatar/mailman2#6]
I am using mailman2:stable and, after some faffing about, I have it running on self-signed certificates. However I note that if I want to supply my own certificates that the Dockerfile exposes the exim ssl directory, but not the apache ssl locations: /etc/ssl/certs/ssl-cert-snakeoil.pem and /etc/ssl/private/ssl-cert-snakeoil.key. Also, those paths do not appear to be configurable in any way.

It therefore appears to be impossible to run this with SSL_SELFSIGNED=false.

Have i missed something?

**Comment by Angatar** [comment]
Hi,
Yep, you missed the use of volumes to overwrite the Apache certificate locations. 
You are right that those paths are not configurable but you simply need to overwrite /etc/ssl/certs/ssl-cert-snakeoil.pem and /etc/ssl/private/ssl-cert-snakeoil.key with your own certificate files.

As explained in the part of the documentation entitled [Setting HTTPS](https://github.com/Angatar/mailman2#setting-https)
So, the docker run should looks like the following:

<pre>
$ docker run --rm -d --name mailman \
             --add-host mails.example.com:127.0.0.1 \
             --hostname mails.example.com \
             -p 80:80 -p 443:443 -p 25:25 -p 465:465 -p 587:587 \
             -e URL_HOST=lists.example.com \
             -e EMAIL_HOST=mails.example.com \
             -e LIST_ADMIN=youremail@example.com \
             -e MASTER_PASSWORD="example" \
             -e URL_PATTERN="https" \
             -e SSL_FROM_CONTAINER="true" \
             -e SSL_SELFSIGNED="false" \
             <b>-v PATH/customcert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem \
             -v PATH/customcertkey.key:/etc/ssl/private/ssl-cert-snakeoil.key \</b>
             - ...
</pre>

NB: The pre-configured "exposed" paths allow to create anonymous volumes so that it keeps track of important data across different deployments (e.g: the DKIM key is not generated each time to avoid to reconfigure your DNS on each deployment).

**Comment by rapmankin** [comment]
A quick response. Thank you. I had been puzzling over this, but then I'm new to Docker.
