### ISSUE TITLE
Digests don't work because run.sh doesn't start cron

### ISSUE THREAD

**Issue by shevek** [Angatar/mailman2#9]
See title.

cron might need syslog, too.

**Comment by Angatar** [comment]
Hi,
Thanks for reporting this and sorry for the lazy reply due to summertime ;)

I've indeed observed it but we are not using digests with our deployments. Maybe other users have fixed it on their side.
It seems that running the cron service, even with syslog, doesn't fix this digests issue:
Actually the mailman python command line dedicated to send digests with cron is silently doing nothing 
`/usr/bin/python /var/lib/mailman/cron/senddigests`

However, the mailman web interface well permit to trigger manually the dispatch of digests according with users preferences:
'https://xxxxx.xxx/xx/admin/yourlist/?VARHELP=digest/_send_digest_now'

So in addition to start the cron service and add the mailman cronjobs to crontab with
`crontab -u list /var/lib mailman/cron/crontab.in`
 
... we would also have to inspect what are the differences between the ways/contexts mailman cron script and the interfaces call the send_digest_now function in order to fix the mailman cron/senddigests script.
The solution is probably within the `/usr/lib/mailman/Mailman/Digester.py` script

I unfortunately have no time to dig more on this at the moment but I assume you might have already fixed it or might use this information to fix your d3fk/mailman2 docker deployment with the digests issue in a close future ... in this case do not hesitate to create a pull request so that I can merge your solution.

keep me posted.
